In [1]:
array=[4,2,3]

signal_index=[]
for number in array:
    for i in range(number):
        signal_index.append(i)

print(signal_index)

[0, 1, 2, 3, 0, 1, 0, 1, 2]


In [ ]:
y_cl2_flat=torch.flatten(y_cl2, start_dim=1)

In [1]:
import torch
y_cl2 = torch.tensor([
    [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],
     [21, 22, 23, 24]]
])

print("Original Tensor:")
print(y_cl2)
print("Shape:", y_cl2.shape)

Original Tensor:
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
Shape: torch.Size([2, 3, 4])


In [2]:
# Flatten starting from dimension 1 (keeping the first dimension)
y_cl2_flat_1 = torch.flatten(y_cl2, start_dim=1)

print("\nFlattened Tensor (start_dim=1):")
print(y_cl2_flat_1)
print("Shape:", y_cl2_flat_1.shape)



Flattened Tensor (start_dim=1):
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
Shape: torch.Size([2, 12])


In [3]:

# Flatten starting from dimension 0 (flattening the entire tensor)
y_cl2_flat_0 = torch.flatten(y_cl2, start_dim=0)

print("\nFlattened Tensor (start_dim=0):")
print(y_cl2_flat_0)
print("Shape:", y_cl2_flat_0.shape)



Flattened Tensor (start_dim=0):
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24])
Shape: torch.Size([24])


In [4]:

# Flatten starting from dimension 2 (keeping the first two dimensions)
y_cl2_flat_2 = torch.flatten(y_cl2, start_dim=2)

print("\nFlattened Tensor (start_dim=2):")
print(y_cl2_flat_2)
print("Shape:", y_cl2_flat_2.shape)



Flattened Tensor (start_dim=2):
tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])
Shape: torch.Size([2, 3, 4])
